# Generated by Django 4.2.4 on 2023-08-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('datanascimento', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('idadecrianca', models.IntegerField()),
                ('sus', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=70)),
                ('nomecrianca', models.CharField(max_length=40)),
                ('generocrianca', models.CharField(max_length=1)),
            ],
        ),
    ]
