# Generated by Django 4.2.4 on 2023-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereco'),
        ),
    ]
